version: "3.7"
services:

  springboot:
    image: sizzle/spring-boot-backend:latest
    restart: always
    ports: 
      - "8181:8181"

  nginx:
    image: sizzle/nginx_reverse_proxy:latest
    restart: always
    ports: 
      - "80:80"
    
  quasar:
    image: sizzle/quasar_fe:latest
    restart: always
    ports:
      - "8080:80"
  mongodb-dev:
    image: mongo
    container_name: sizzle/mongodb-database
    environment: 
      MONGO_INITDB_DATABASE: test # database name to give
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    
    volumes: 
      - ./mongo-volume:/data/db
    ports: 
    - "27017-27019:27017-27019"